baseURL = 'http://example.org/'
languageCode = 'en-us'
# 网站标题
title = 'OverlookArt'

#主题 模块安装的主题不需要设置，theme文件夹下的主题需要设置
theme = 'overlookart'

# 版权
copyright = 'OverlookArt'

# 默认内容语言
defaultContentLanguage = 'en'

defaultContentLanguageInSubdir = true

enableGitInfo = true

# 模块配置
[module]
[[module.imports]]
# 有效的 go 模块路径
#  path = 'github.com/panr/hugo-theme-terminal'

# 参数配置
[params]
