baseURL = 'http://example.org/'
languageCode = 'en-us'
# 网站标题
title = 'OverlookArt'

#主题 模块安装的主题不需要设置，theme文件夹下的主题需要设置
#theme = 'terminal'

# 版权
copyright = 'OverlookArt'

# 默认内容语言
defaultContentLanguage = 'en'

defaultContentLanguageInSubdir = true

# 菜单配置
[menu]
[[menu.main]]
  identifier = 'about'
  name = '关于'
  pre = "<i class='fa fa-heart'></i>"
  url = '/about/'
  weight = -110
  [menu.main.params]
    class = 'highlight-menu-item'

# 模块配置
[module]
[[module.imports]]
  path = 'github.com/panr/hugo-theme-terminal'

# 参数配置
[params]
themeColor = "orange"
fullWidthTheme = false
centerTheme = false